homework:
	# clang++ homework1.cpp -lpthread
	# clang++ homework2.cpp -lpthread
	clang++ homework3.cpp -lpthread
signal:
	clang++ signal3.cpp -lpthread
	# clang++ signal2.cpp -lpthread
	# clang++ signal.cpp -lpthread
problem2:
	clang++ problem2.cpp -lpthread
problem:
	clang++ pthread_problem.cpp -lpthread
create:
	clang++ create_pthread.cpp -lpthread
